## 첫 번째 딥러닝 예제 : 폐암 수술 환자의 생존율 예측하기 실습

폐암 수술 환자의 생존율 예측
- 데이터 준비
(1) 딥러닝 모델 설정
(2) 모델 컴파일
(3) 모델 실행 (학습)

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [2]:
import warnings
warnings.filterwarnings(action='ignore')

In [3]:
import numpy as np

In [4]:
# 준비된 수술 환자 데이터를 불러 오기
Data_set = np.loadtxt("../data/ThoraricSurgery.csv", delimiter=",")
Data_set.shape
Data_set[:3]

(470, 18)

array([[293.  ,   1.  ,   3.8 ,   2.8 ,   0.  ,   0.  ,   0.  ,   0.  ,
          0.  ,   0.  ,  12.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88,   2.16,   1.  ,   0.  ,   0.  ,   0.  ,
          1.  ,   1.  ,  14.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19,   2.5 ,   1.  ,   0.  ,   0.  ,   0.  ,
          1.  ,   0.  ,  11.  ,   0.  ,   0.  ,   1.  ,   1.  ,   0.  ,
         66.  ,   1.  ]])

In [5]:
X_feature = Data_set[:, 1:-1]
y_target = Data_set[:, -1]
X_feature[:3]
y_target[:3]

array([[ 1.  ,  3.8 ,  2.8 ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        12.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 62.  ],
       [ 2.  ,  2.88,  2.16,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,
        14.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 60.  ],
       [ 2.  ,  3.19,  2.5 ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,
        11.  ,  0.  ,  0.  ,  1.  ,  1.  ,  0.  , 66.  ]])

array([0., 0., 1.])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_feature, y_target, test_size=0.1, random_state=1)
X_train.shape

(423, 16)

In [7]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential # 신경망 모델
from keras.layers import Dense # 신경망 층을 정의

In [8]:
# 1
model = Sequential()

# 2
model.add(Dense(units=30, input_dim=16, activation='linear'))
model.add(Dense(units=1, activation='sigmoid'))

# 3
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics='Accuracy')

In [9]:
# 4
model.fit(x=X_train, y=y_train, epochs=300, batch_size=5)

Epoch 1/300
85/85 [==============================] - 0s 426us/step - loss: 0.7725 - Accuracy: 0.8038
Epoch 2/300
85/85 [==============================] - 0s 370us/step - loss: 0.4678 - Accuracy: 0.8487
Epoch 3/300
85/85 [==============================] - 0s 375us/step - loss: 0.4443 - Accuracy: 0.8463
Epoch 4/300
85/85 [==============================] - 0s 394us/step - loss: 0.4417 - Accuracy: 0.8487
Epoch 5/300
85/85 [==============================] - 0s 371us/step - loss: 0.4797 - Accuracy: 0.8511
Epoch 6/300
85/85 [==============================] - 0s 373us/step - loss: 0.5144 - Accuracy: 0.8369
Epoch 7/300
85/85 [==============================] - 0s 379us/step - loss: 0.4358 - Accuracy: 0.8487
Epoch 8/300
85/85 [==============================] - 0s 386us/step - loss: 0.4693 - Accuracy: 0.8416
Epoch 9/300
85/85 [==============================] - 0s 379us/step - loss: 0.4518 - Accuracy: 0.8487
Epoch 10/300
85/85 [==============================] - 0s 382us/step - loss: 0.4307 - Accura

85/85 [==============================] - 0s 358us/step - loss: 0.4388 - Accuracy: 0.8416
Epoch 82/300
85/85 [==============================] - 0s 360us/step - loss: 0.4182 - Accuracy: 0.8487
Epoch 83/300
85/85 [==============================] - 0s 362us/step - loss: 0.4326 - Accuracy: 0.8440
Epoch 84/300
85/85 [==============================] - 0s 356us/step - loss: 0.4377 - Accuracy: 0.8322
Epoch 85/300
85/85 [==============================] - 0s 358us/step - loss: 0.4486 - Accuracy: 0.8392
Epoch 86/300
85/85 [==============================] - 0s 358us/step - loss: 0.4735 - Accuracy: 0.8416
Epoch 87/300
85/85 [==============================] - 0s 361us/step - loss: 0.4425 - Accuracy: 0.8440
Epoch 88/300
85/85 [==============================] - 0s 353us/step - loss: 0.4161 - Accuracy: 0.8534
Epoch 89/300
85/85 [==============================] - 0s 348us/step - loss: 0.4260 - Accuracy: 0.8440
Epoch 90/300
85/85 [==============================] - 0s 358us/step - loss: 0.4349 - Accuracy: 

85/85 [==============================] - 0s 357us/step - loss: 0.4301 - Accuracy: 0.8487
Epoch 161/300
85/85 [==============================] - 0s 353us/step - loss: 0.4215 - Accuracy: 0.8558
Epoch 162/300
85/85 [==============================] - 0s 354us/step - loss: 0.4161 - Accuracy: 0.8534
Epoch 163/300
85/85 [==============================] - 0s 359us/step - loss: 0.4296 - Accuracy: 0.8345
Epoch 164/300
85/85 [==============================] - 0s 354us/step - loss: 0.4138 - Accuracy: 0.8463
Epoch 165/300
85/85 [==============================] - 0s 356us/step - loss: 0.4201 - Accuracy: 0.8487
Epoch 166/300
85/85 [==============================] - 0s 355us/step - loss: 0.4192 - Accuracy: 0.8534
Epoch 167/300
85/85 [==============================] - 0s 357us/step - loss: 0.4353 - Accuracy: 0.8416
Epoch 168/300
85/85 [==============================] - 0s 359us/step - loss: 0.4148 - Accuracy: 0.8440
Epoch 169/300
85/85 [==============================] - 0s 348us/step - loss: 0.4472 - A

85/85 [==============================] - 0s 372us/step - loss: 0.4253 - Accuracy: 0.8511
Epoch 240/300
85/85 [==============================] - 0s 364us/step - loss: 0.4441 - Accuracy: 0.8369
Epoch 241/300
85/85 [==============================] - 0s 359us/step - loss: 0.4249 - Accuracy: 0.8487
Epoch 242/300
85/85 [==============================] - 0s 355us/step - loss: 0.4237 - Accuracy: 0.8416
Epoch 243/300
85/85 [==============================] - 0s 347us/step - loss: 0.4066 - Accuracy: 0.8440
Epoch 244/300
85/85 [==============================] - 0s 349us/step - loss: 0.4326 - Accuracy: 0.8440
Epoch 245/300
85/85 [==============================] - 0s 360us/step - loss: 0.4292 - Accuracy: 0.8416
Epoch 246/300
85/85 [==============================] - 0s 359us/step - loss: 0.4294 - Accuracy: 0.8534
Epoch 247/300
85/85 [==============================] - 0s 360us/step - loss: 0.4162 - Accuracy: 0.8463
Epoch 248/300
85/85 [==============================] - 0s 358us/step - loss: 0.4227 - A

In [10]:
# 평가
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 1ms/step - loss: 0.3546 - Accuracy: 0.8511


[0.3545916974544525, 0.8510638475418091]

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                510       
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 541 (2.11 KB)
Trainable params: 541 (2.11 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
import pandas as pd
data_df = pd.DataFrame(Data_set)
data_df[0] = data_df[0].astype(int)
data_df.set_index(0, inplace=True)
data_df.sort_index(inplace=True)
data_df.index.unique()

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       461, 462, 463, 464, 465, 466, 467, 468, 469, 470],
      dtype='int64', name=0, length=470)